import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "URL Shortener",
  description: "Generated by create MAS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className=" bg-gray-800">
         <Navbar />
        {children}
      </body>
    </html>
  );
}
